### ISSUE TITLE
valuerror

### ISSUE THREAD

**Issue by tangh18** [saturn-lab/audioPlot#3]
command: python3 wavefile2waveform.py ./wavefile

Traceback (most recent call last):
  File "wavfile2waveform.py", line 47, in <module>
    ConvertAudioToWaveform(sys.argv[1])
  File "wavfile2waveform.py", line 43, in ConvertAudioToWaveform
    ConvertFile2Waveform(audio, dir_out)
  File "wavfile2waveform.py", line 15, in ConvertFile2Waveform
    rate, data =readWav(audio)
  File "/home/ryan/Documents/audioPlot/wavReader.py", line 47, in readWav
    sps, data = _parseData(buf)
  File "/home/ryan/Documents/audioPlot/wavReader.py", line 40, in _parseData
    data = numpy.frombuffer(buf[itr + 8: itr + 8 + size], dtype=numpy.float32)
ValueError: buffer size must be a multiple of element size

**Comment by tangh18** [comment]
environment: ubuntu 18.04 lts

**Comment by zhenchen3419** [comment]
git pull 最新版本的wavReader.py
