### ISSUE TITLE
audioPlot中step3.2转换时报错

### ISSUE THREAD

**Issue by BertramRay** [saturn-lab/audioPlot#4]
**Step 3.2 Convert wavfiles to waveform**
$python wavfile2waveform.py ./wavfile
put waveforms into images/waveform/
**在进行这一步时命令行界面显示如下错误：**
Traceback (most recent call last):
  File "wavfile2waveform.py", line 47, in <module>
    ConvertAudioToWaveform(sys.argv[1])
  File "wavfile2waveform.py", line 43, in ConvertAudioToWaveform
    ConvertFile2Waveform(audio, dir_out)
  File "wavfile2waveform.py", line 15, in ConvertFile2Waveform
    rate, data =readWav(audio)
  File "C:\Users\10344\audioPlot\wavReader.py", line 47, in readWav
    sps, data = _parseData(buf)
  File "C:\Users\10344\audioPlot\wavReader.py", line 40, in _parseData
    data = numpy.frombuffer(buf[itr + 8: itr + 8 + size], dtype=numpy.float32)
**ValueError: buffer size must be a multiple of element size**

**Comment by zhenchen3419** [comment]
git pull下载最新版本的wavReader.py
